### ISSUE TITLE
[Bug] When opening the site with the configured keys the code breaks by the API return

### ISSUE THREAD

**Issue by nklowns** [joscha0/clickup-time-track#1]
### Steps to Reproduce

1. Open the website https://clickup.960.eu/settings
1. Fill the api_key and team_id
1. go to Dashboard

### Expected Behavior

- expected behavior

Should display the content

### Current Behavior

- current behavior

![image](https://user-images.githubusercontent.com/17345221/214457035-b590a651-f75d-4b85-992d-fb38094798d2.png)
![image](https://user-images.githubusercontent.com/17345221/214457044-a1aa98e5-90bc-4441-929d-97ad5e4ca804.png)
![image](https://user-images.githubusercontent.com/17345221/214457053-7e5e001b-1151-4203-ae9b-50dbbebe15f1.png)

### Possible Solution

- possible solution

One should observe if the api returns the same content, and handle when certain expected properties do not come.

**Comment by joscha0** [comment]
Does it work now?
I assume it is because you track time that is unassigned to a task. 
I can not recreate this issue because I am not on a ClickUp Business Plan.

**Comment by nklowns** [comment]
It's working, thank you
